apiVersion: v1
kind: Secret
metadata:
  name: scribe-secret
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
    tekton.dev/docker-0: https://gcr.io
type: Opaque
stringData:
  client_id: $(client_id)
  client_secret: $(client_secret)
