---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: valint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: CLI, valint
    tekton.dev/displayName: valint
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to generate sbom and verify the sbom
  workspaces:
    - name: source-dir
      optional: true
  params:
    - name: args
      description: The repository URL to inspect
      type: string
    - name: scribe-secret
      description: Scribe secret name
      type: string
    - name: image-version-sha
      description: sha of the valint image to be used
      default: sha256:961e3e0292338e11f6c5c48645d684aaf05aa76c8e3e6fa2a786628b60c2a11d
    - name: cache-dir
      type: string
      description: "if you use local bom cache"
      default: ""
  steps:
    - name: bom-verify
      image: scribesecuriy.jfrog.io/scribe-docker-public-local/valint@$(params.image-version-sha)
      workingDir: $(workspaces.source-dir.path)
      args:
        - "$(params.args)"
        - "--context-type=tekton"
      volumeMounts:
        - name: $(params.cache-dir)
          mountPath: /root/.cache
      env:
        - name: SCRIBE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: $(params.scribe-secret)
              key: client_id
        - name: SCRIBE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: $(params.scribe-secret)
              key: client_secret
